#!/bin/sh
alias j='z'
alias f='zi'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias afk="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias list_systemctl="systemctl list-unit-files --state=enabled"

# custom stuff
alias v='nvim'
alias ccht='curl cht.sh'
alias cht='cht.sh'
alias down='downgrade'
# alias ls='exa -al --color=always --group-directories-first'
alias ls='ls_extended -Alsh'
alias usb='sudo mount --uuid AB2D-8744 /run/media/brian'
alias green='rgb_keyboard -l fixed -c 04ff04'
alias multi='rgb_keyboard -l swirl -c multi'
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias mp='mdpdf'
alias dc='clipdel -d'
alias dca='clipdel -d .'
alias tshark='tshark --color'
alias update='topgrade --skip-notify'
alias update-test='topgrade -n'
# alias yay='paru'
alias pi='sudo pacman -S'
alias pr='sudo pacman -R'
alias pra='sudo pacman -Rns'
alias bd='cd ..'
alias pd='cd -'
alias sudoe='sudoedit nvim'
# alias yt='youtube-dl'
alias yt='yt-dlp'
alias pcem='cd ~/Documents/PCemV17Linux; ./pcem'
alias sudo='doas'
alias ga='git add .'
alias gc='git commit -m'
alias gp='git push'

# System Updates
alias pacsyu="sudo pacman -Syyu"                 # update only standard pkgs
alias yaysua="yay -Sua --noconfirm"              # update only AUR pkgs (yay)
alias yaysyu="yay -Syu"                          # update standard pkgs and AUR pkgs (yay)
alias parsua="paru -Sua --noconfirm"             # update only AUR pkgs (paru)
alias parsyu="paru -Syu --noconfirm"             # update standard pkgs and AUR pkgs (paru)
alias unlock="sudo rm /var/lib/pacman/db.lck"    # remove pacman lock
alias cleanup="sudo pacman -Rns (pacman -Qtdq"  # remove orphaned packages
