#!/bin/sh
HISTFILE=$HOME/.config/zsh/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.miniconda/bin:$PATH
export HISTFILE=$HOME/.config/zsh/.zsh_history
# eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
export CM_SELECTIONS="clipboard"
export CM_LAUNCHER="rofi"
export VISUAL="nvim"
